// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "authkey": string;
      "targetLanguage": string;
      "translateMode": string;
      "translateModel": string;
      "enhanceCompatibility": boolean;
      "autoTranslate": boolean;
      "autoOpenPDF": boolean;
      "ocrWorkaround": boolean;
      "fakeUserId": string;
      "enableShortcuts": boolean;
    };
  }
}
